Repository paketo-buildpacks/oracle, pull requests merged in 2024-04, with the labels that each got.

#194 Document BPL_JVM_CLASS_ADJUSTMENT
  README.md
Labels: type:documentation, semver:patch

#199 Add Java 22
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-jdk-22.yml
  .github/workflows/pb-update-native-image-22.yml
  buildpack.toml
Labels: type:dependency-upgrade, semver:minor

#200 Add ARM64 support
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-jdk-17-arm-64.yml
  .github/workflows/pb-update-jdk-21-arm-64.yml
  .github/workflows/pb-update-jdk-22-arm-64.yml
  .github/workflows/pb-update-native-image-17-arm-64.yml
  .github/workflows/pb-update-native-image-21-arm-64.yml
  .github/workflows/pb-update-native-image-22-arm-64.yml
  .gitignore
  README.md
  buildpack.toml
  scripts/build.sh
Labels: semver:minor, type:enhancement

#219 Fix arm64 for graal 17
  .github/pipeline-descriptor.yml
Labels: type:bug, semver:patch
